In [1]:
import numpy as np

In [2]:
class Queue:
    def __init__(self):    #magic methods
        self.__end = -1
        self.__size = 0
        self.__data = np.zeros((10), dtype=int)
        
    def isFull(self):
        return self.__size == len(self.__data)
    def isEmpty(self):
        return self.__size == 0
    
    def size(self):
        return self.__size
    
    def add(self,value):
        if self.isFull():
            print("Queue is Full")
        else:
            self.__end += 1
            self.__data[self.__end] = value
            self.__size += 1
            
    def remove(self):
        removed = self.__data[0]
        if self.isEmpty():
            print("Queue is Empty")
        else:
            for i in range(self.__end+1):      # or 1 to self.__size
                self.__data[i] = self.__data[i+1]
            self.__end -= 1
            self.__size -= 1
            return removed
        
    def __repr__(self):     #magic methods
        return str(self.__data[:self.__end+1])

In [3]:
q = Queue()

In [4]:
q.add(2)
q.add(25)
q.add(32)
q.add(72)

In [5]:
print(q)

[ 2 25 32 72]


In [6]:
q.remove()

2

In [7]:
print(q)

[25 32 72]


## Circular Queue

In [9]:
class CircularQueue:
    def __init__(self):    #magic methods
        self.__front = 0
        self.__end = 0
        self.__size = 0
        self.__data = np.zeros((10), dtype=int)
        
    def isFull(self):
        return self.__size == len(self.__data)
    def isEmpty(self):
        return self.__size == 0
    
    def add(self,value):
        if self.isFull():
            print("Queue is Full")
        else:
            self.__data[self.__end] = value
            self.__end += 1
            self.__end = self.__end % len(self.__data)
            
            self.__size += 1 
            
    def remove(self):
        removed = self.__data[self.__front]
        if self.isEmpty():
            print("Queue is Empty")
            return None
        else:
            self.__front += 1
            self.__front =  self.__front % len(self.__data)
            self.__size -= 1
            return removed
        
    def __repr__(self):     #magic methods
        if self.__front < self.__end:
            return str(self.__data[self.__front : self.__end])
        else:
            cut1 = self.__data[self.__front:]
            cut2 = self.__data[0:self.__end]
            cut = np.concatenate((cut2,cut1))
            return f'[{",".join(map(str,cut))}]'    # f strings 

In [10]:
q1 = CircularQueue()
q1.add(2)
q1.add(25)
q1.add(38)
q1.add(72)

In [11]:
print(q1)

[ 2 25 38 72]


In [12]:
cq = CircularQueue()
for i in range(10):
    cq.add(i+1)

In [13]:
print(cq)

[1,2,3,4,5,6,7,8,9,10]


In [ ]:
q1.remove()

## Stack using Queue

#### Add Efficient

In [ ]:
class SUQ:
    
    def __init__(self):
        self.q1 = Queue()
        self.q2 = Queue()
        
    def add(self,value):
        self.q1.add(value)
        
    def remove(self):
        while self.q1.size() != 1:
            self.q2.add(self.q1.remove())
        removed = self.q1.remove()
        self.q1, self.q2  = self.q2, self.q1
        return removed 
    def dis(self):
        print(self.q1)

In [ ]:
suq = SUQ()

In [ ]:
suq.add(12)
suq.add(21)
suq.add(112)
suq.dis()
suq.remove()
suq.dis()

#### Remove Efficient

In [ ]:
class SUQ1:
    
    def __init__(self):
        self.q1 = Queue()
        self.q2 = Queue()
        
    def add(self,value):
            self.q2.add(value)
            while not self.q1.isEmpty():
                self.q2.add(self.q1.remove())
            self.q1, self.q2  = self.q2, self.q1
    
    def remove(self):
        self.q1.remove()
        
    def dis(self):
        print(self.q1)

In [ ]:
saq = SUQ1()

In [ ]:
saq.add(23)
saq.add(3)
saq.add(73)
saq.dis()