In [1]:
import numpy as np

In [3]:
a = np.array([12,34,67])

In [5]:
a.shape

(3,)

In [6]:
a.size

3

In [7]:
a.dtype #python int datatypes int8 - int 64 - unassigned int

dtype('int32')

In [9]:
b = np.array([12,34,62], dtype = np.int8) #to explicitly determine the datatype

In [11]:
b.dtype

dtype('int8')

In [18]:
c = np.array([[11,12],[22,23]])

In [19]:
c.size

4

In [20]:
c.shape

(2, 2)

In [21]:
d = np.array([[11,12],[22,23,24]])

In [22]:
d.size

2

In [23]:
d.shape

(2,)

In [25]:
f = np.array([[[[[1]]]]])

In [26]:
f.size

1

In [27]:
f.shape

(1, 1, 1, 1, 1)

In [29]:
f = np.array([[[[[[1]]]]],[[[[[1]]]]]])
f.shape

(2, 1, 1, 1, 1, 1)

In [36]:
e = np.array([[[1],[2],[3]],[[1],[2],[3]]])

In [37]:
e.shape

(2, 3, 1)

In [31]:
np.array(range(100))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [32]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [33]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [35]:
np.arange(20,10,-4)

array([20, 16, 12])

In [38]:
first = np.arange(12)

In [40]:
second = first.reshape(3,1,2,1,2) # can reshape items into any no. of dimensions of same range

In [41]:
second

array([[[[[ 0,  1]],

         [[ 2,  3]]]],



       [[[[ 4,  5]],

         [[ 6,  7]]]],



       [[[[ 8,  9]],

         [[10, 11]]]]])

In [42]:
second.shape

(3, 1, 2, 1, 2)

In [43]:
first[0] = 1000

In [44]:
second # proving that they are potinting to the same object

array([[[[[1000,    1]],

         [[   2,    3]]]],



       [[[[   4,    5]],

         [[   6,    7]]]],



       [[[[   8,    9]],

         [[  10,   11]]]]])

In [46]:
third = first.reshape(2,2,3)

In [47]:
third

array([[[1000,    1,    2],
        [   3,    4,    5]],

       [[   6,    7,    8],
        [   9,   10,   11]]])

In [48]:
fourth  = first.astype(float) #astype is immutable operation which makes a new python object
                                #as well as native object

In [49]:
fourth

array([1000.,    1.,    2.,    3.,    4.,    5.,    6.,    7.,    8.,
          9.,   10.,   11.])

In [50]:
np.zeros?

Docstring:
zeros(shape, dtype=float, order='C')

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional
    Whether to store multidimensional data in C- or Fortran-contiguous
    (row- or column-wise) order in memory.

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Also
--------
zeros_like : Return an array of zeros with shape and type of input.
ones_like : Return an array of ones with shape and type of input.
empty_like : Return an empty array with shape and type of input.
ones : Return a new array setting values to one.
empty : Return a new uninitialized array.

Examples
--------
>>> np.zeros(5)
array([ 0.,  0.,  0.,  0.,  0.])

>>> np.zeros((5,), dtype=int)
array([0, 0, 0,

In [51]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [53]:
np.zeros((10,10), dtype= int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [55]:
np.full((5,5),10) # 5*5 array of element 10

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])